### ISSUE TITLE
"Related posts" links are protocol-relative and broken.

### ISSUE THREAD

**Issue by michaelsproul** [MaikKlein/maikklein.github.io#1]
Currently the links at the bottom of your blog look like this:

```
<a href="//2015/01/11/Evaluating-D-for-games/"></a>
```

This gets translated by both Firefox and Chrome into `http://2015/01/11/Evaluating-D-for-games/`, which is clearly bad. I think for (domain) relative URLs you can simply use a single slash and the browser will continue to use whatever scheme/protocol it was previously using. I tried this just now and it worked, but the relevant RFC is dead (weird?).

http://tools.ietf.org/html/rfc3986

Probably a bug in the Jekyll theme you're using.

Regards,

Michael

**Comment by MaikKlein** [comment]
Thanks for the catch! Yes the theme had a small bug, it should work now.
